name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore QuizAPI/QuizAPI.sln

    - name: Build
      run: dotnet build QuizAPI/QuizAPI.sln --no-restore

    - name: Run tests
      run: dotnet test QuizAPI/QuizAPI.sln --no-build --verbosity normal
